/**
 * Level definitions for 2D puzzle game
 */
import { Level2D } from './types'

// All game levels organized by difficulty
export const LEVELS: Level2D[] = [
  // === EASY LEVELS ===
  {
    id: 0,
    name: 'First Light',
    nameZh: '初见光芒',
    description: 'Rotate the polarizer to let light through to the sensor',
    descriptionZh: '旋转偏振片让光通过并到达传感器',
    hint: 'Match the polarizer angle with the light polarization',
    hintZh: '将偏振片角度与光的偏振方向对齐',
    difficulty: 'easy',
    gridSize: { width: 100, height: 100 },
    components: [
      { id: 'e1', type: 'emitter', x: 50, y: 10, angle: 0, polarizationAngle: 0, direction: 'down', locked: true },
      { id: 'p1', type: 'polarizer', x: 50, y: 50, angle: 0, polarizationAngle: 90, locked: false },
      { id: 's1', type: 'sensor', x: 50, y: 90, angle: 0, requiredIntensity: 80, requiredPolarization: 0, locked: true },
    ],
  },
  {
    id: 1,
    name: 'The Mirror',
    nameZh: '镜面反射',
    description: 'Use the mirror to redirect light to the sensor',
    descriptionZh: '使用镜子将光重新引导至传感器',
    difficulty: 'easy',
    gridSize: { width: 100, height: 100 },
    components: [
      { id: 'e1', type: 'emitter', x: 20, y: 20, angle: 0, polarizationAngle: 0, direction: 'right', locked: true },
      { id: 'm1', type: 'mirror', x: 80, y: 20, angle: 45, locked: false },
      { id: 's1', type: 'sensor', x: 80, y: 80, angle: 0, requiredIntensity: 80, locked: true },
    ],
  },
  {
    id: 2,
    name: 'Crossed Polarizers',
    nameZh: '正交偏振',
    description: 'Two perpendicular polarizers block all light. Find a way through!',
    descriptionZh: '两个垂直的偏振片会阻挡所有光。找到通过的方法！',
    hint: 'A 45° polarizer between crossed polarizers allows some light through',
    hintZh: '在正交偏振片之间放置45°偏振片可以让部分光通过',
    difficulty: 'easy',
    gridSize: { width: 100, height: 100 },
    components: [
      { id: 'e1', type: 'emitter', x: 50, y: 8, angle: 0, polarizationAngle: 0, direction: 'down', locked: true },
      { id: 'p1', type: 'polarizer', x: 50, y: 30, angle: 0, polarizationAngle: 0, locked: true },
      { id: 'p2', type: 'polarizer', x: 50, y: 50, angle: 0, polarizationAngle: 45, locked: false },
      { id: 'p3', type: 'polarizer', x: 50, y: 70, angle: 0, polarizationAngle: 90, locked: true },
      { id: 's1', type: 'sensor', x: 50, y: 92, angle: 0, requiredIntensity: 20, locked: true },
    ],
  },
  // === MEDIUM LEVELS ===
  {
    id: 3,
    name: 'L-Shaped Path',
    nameZh: 'L形路径',
    description: 'Guide light around the corner to reach the sensor',
    descriptionZh: '引导光线绕过转角到达传感器',
    difficulty: 'medium',
    gridSize: { width: 100, height: 100 },
    openEnded: true,
    components: [
      { id: 'e1', type: 'emitter', x: 15, y: 20, angle: 0, polarizationAngle: 45, direction: 'right', locked: true },
      { id: 'm1', type: 'mirror', x: 75, y: 20, angle: 45, locked: false },
      { id: 'p1', type: 'polarizer', x: 75, y: 50, angle: 0, polarizationAngle: 45, locked: false },
      { id: 's1', type: 'sensor', x: 75, y: 85, angle: 0, requiredIntensity: 60, requiredPolarization: 45, locked: true },
    ],
  },
  {
    id: 4,
    name: 'Rotator Magic',
    nameZh: '旋光魔法',
    description: 'Use the wave plate to rotate polarization without losing intensity',
    descriptionZh: '使用波片旋转偏振方向而不损失强度',
    difficulty: 'medium',
    gridSize: { width: 100, height: 100 },
    components: [
      { id: 'e1', type: 'emitter', x: 50, y: 10, angle: 0, polarizationAngle: 0, direction: 'down', locked: true },
      { id: 'r1', type: 'rotator', x: 50, y: 40, angle: 0, rotationAmount: 45, locked: false },
      { id: 'p1', type: 'polarizer', x: 50, y: 65, angle: 0, polarizationAngle: 45, locked: true },
      { id: 's1', type: 'sensor', x: 50, y: 90, angle: 0, requiredIntensity: 90, requiredPolarization: 45, locked: true },
    ],
  },
  {
    id: 5,
    name: 'Split Decision',
    nameZh: '分光选择',
    description: 'The splitter creates two beams with perpendicular polarizations',
    descriptionZh: '分光器产生两束偏振方向垂直的光',
    hint: 'Choose which beam to direct to the sensor',
    hintZh: '选择哪束光引导至传感器',
    difficulty: 'medium',
    gridSize: { width: 100, height: 100 },
    openEnded: true,
    components: [
      { id: 'e1', type: 'emitter', x: 15, y: 50, angle: 0, polarizationAngle: 45, direction: 'right', locked: true },
      { id: 'sp1', type: 'splitter', x: 50, y: 50, angle: 0, locked: true },
      { id: 'm1', type: 'mirror', x: 50, y: 20, angle: 135, locked: false },
      { id: 's1', type: 'sensor', x: 85, y: 50, angle: 0, requiredIntensity: 40, requiredPolarization: 0, locked: true },
    ],
  },
  // === HARD LEVELS ===
  {
    id: 6,
    name: 'Dual Sensors',
    nameZh: '双传感器',
    description: 'Activate both sensors with different polarizations',
    descriptionZh: '用不同偏振方向激活两个传感器',
    difficulty: 'hard',
    gridSize: { width: 100, height: 100 },
    openEnded: true,
    components: [
      { id: 'e1', type: 'emitter', x: 15, y: 50, angle: 0, polarizationAngle: 45, direction: 'right', locked: true },
      { id: 'sp1', type: 'splitter', x: 45, y: 50, angle: 0, locked: true },
      { id: 'm1', type: 'mirror', x: 45, y: 20, angle: 135, locked: false },
      { id: 'm2', type: 'mirror', x: 85, y: 50, angle: 45, locked: false },
      { id: 's1', type: 'sensor', x: 85, y: 20, angle: 0, requiredIntensity: 40, requiredPolarization: 90, locked: true },
      { id: 's2', type: 'sensor', x: 85, y: 80, angle: 0, requiredIntensity: 40, requiredPolarization: 0, locked: true },
    ],
  },
  {
    id: 7,
    name: 'Maze of Light',
    nameZh: '光之迷宫',
    description: 'Navigate through multiple mirrors and polarizers',
    descriptionZh: '在多个镜子和偏振片之间导航',
    difficulty: 'hard',
    gridSize: { width: 100, height: 100 },
    openEnded: true,
    components: [
      { id: 'e1', type: 'emitter', x: 10, y: 10, angle: 0, polarizationAngle: 0, direction: 'right', locked: true },
      { id: 'm1', type: 'mirror', x: 50, y: 10, angle: 45, locked: false },
      { id: 'p1', type: 'polarizer', x: 50, y: 35, angle: 0, polarizationAngle: 0, locked: false },
      { id: 'm2', type: 'mirror', x: 50, y: 55, angle: 135, locked: false },
      { id: 'r1', type: 'rotator', x: 75, y: 55, angle: 0, rotationAmount: 90, locked: false },
      { id: 'm3', type: 'mirror', x: 90, y: 55, angle: 45, locked: false },
      { id: 's1', type: 'sensor', x: 90, y: 90, angle: 0, requiredIntensity: 50, requiredPolarization: 90, locked: true },
    ],
  },
  {
    id: 8,
    name: 'Precision Cascade',
    nameZh: '精确级联',
    description: 'Fine-tune multiple polarizers to achieve exact intensity',
    descriptionZh: '精调多个偏振片达到精确强度',
    difficulty: 'hard',
    gridSize: { width: 100, height: 100 },
    components: [
      { id: 'e1', type: 'emitter', x: 50, y: 5, angle: 0, polarizationAngle: 0, direction: 'down', locked: true },
      { id: 'p1', type: 'polarizer', x: 50, y: 22, angle: 0, polarizationAngle: 20, locked: false },
      { id: 'p2', type: 'polarizer', x: 50, y: 40, angle: 0, polarizationAngle: 40, locked: false },
      { id: 'p3', type: 'polarizer', x: 50, y: 58, angle: 0, polarizationAngle: 60, locked: false },
      { id: 'p4', type: 'polarizer', x: 50, y: 76, angle: 0, polarizationAngle: 80, locked: false },
      { id: 's1', type: 'sensor', x: 50, y: 95, angle: 0, requiredIntensity: 50, locked: true },
    ],
  },
  // === EXPERT LEVELS ===
  {
    id: 9,
    name: 'Quantum Interference',
    nameZh: '量子干涉',
    description: 'Advanced puzzle: route light through complex optical system',
    descriptionZh: '高级关卡：通过复杂光学系统引导光线',
    difficulty: 'expert',
    gridSize: { width: 100, height: 100 },
    openEnded: true,
    components: [
      { id: 'e1', type: 'emitter', x: 10, y: 25, angle: 0, polarizationAngle: 45, direction: 'right', locked: true },
      { id: 'e2', type: 'emitter', x: 10, y: 75, angle: 0, polarizationAngle: 45, direction: 'right', locked: true },
      { id: 'sp1', type: 'splitter', x: 35, y: 25, angle: 0, locked: true },
      { id: 'sp2', type: 'splitter', x: 35, y: 75, angle: 0, locked: true },
      { id: 'm1', type: 'mirror', x: 65, y: 25, angle: 45, locked: false },
      { id: 'm2', type: 'mirror', x: 65, y: 75, angle: 135, locked: false },
      { id: 'p1', type: 'polarizer', x: 65, y: 50, angle: 0, polarizationAngle: 45, locked: false },
      { id: 's1', type: 'sensor', x: 90, y: 50, angle: 0, requiredIntensity: 60, locked: true },
    ],
  },
  {
    id: 10,
    name: 'The Grand Challenge',
    nameZh: '终极挑战',
    description: 'Master all optical principles to complete this puzzle',
    descriptionZh: '掌握所有光学原理来完成这个谜题',
    difficulty: 'expert',
    gridSize: { width: 100, height: 100 },
    openEnded: true,
    components: [
      { id: 'e1', type: 'emitter', x: 5, y: 50, angle: 0, polarizationAngle: 0, direction: 'right', locked: true },
      { id: 'r1', type: 'rotator', x: 20, y: 50, angle: 0, rotationAmount: 45, locked: false },
      { id: 'sp1', type: 'splitter', x: 40, y: 50, angle: 0, locked: true },
      { id: 'm1', type: 'mirror', x: 40, y: 20, angle: 135, locked: false },
      { id: 'p1', type: 'polarizer', x: 65, y: 20, angle: 0, polarizationAngle: 90, locked: false },
      { id: 'm2', type: 'mirror', x: 80, y: 20, angle: 45, locked: false },
      { id: 'm3', type: 'mirror', x: 65, y: 50, angle: 45, locked: false },
      { id: 'p2', type: 'polarizer', x: 65, y: 75, angle: 0, polarizationAngle: 0, locked: false },
      { id: 's1', type: 'sensor', x: 80, y: 50, angle: 0, requiredIntensity: 30, requiredPolarization: 90, locked: true },
      { id: 's2', type: 'sensor', x: 65, y: 90, angle: 0, requiredIntensity: 30, requiredPolarization: 0, locked: true },
    ],
  },
]
