export { GamePage } from './GamePage'
export { Game2DPage } from './Game2DPage'
export { HomePage } from './HomePage'
export { DemosPage } from './DemosPage'
export { HardwarePage } from './HardwarePage'
export { CardGamePage } from './CardGamePage'
export { MerchandisePage } from './MerchandisePage'
