/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as MerchandiseRouteImport } from './routes/merchandise'
import { Route as CourseRouteImport } from './routes/course'
import { Route as SplatRouteImport } from './routes/$'
import { Route as DemosIndexRouteImport } from './routes/demos.index'

const LearnLazyRouteImport = createFileRoute('/learn')()
const HardwareLazyRouteImport = createFileRoute('/hardware')()
const ChroniclesLazyRouteImport = createFileRoute('/chronicles')()
const IndexLazyRouteImport = createFileRoute('/')()
const ResearchIndexLazyRouteImport = createFileRoute('/research/')()
const GamesIndexLazyRouteImport = createFileRoute('/games/')()
const GalleryIndexLazyRouteImport = createFileRoute('/gallery/')()
const CalcIndexLazyRouteImport = createFileRoute('/calc/')()
const ResearchApplicationsLazyRouteImport = createFileRoute(
  '/research/applications',
)()
const GamesEscapeLazyRouteImport = createFileRoute('/games/escape')()
const GamesDetectiveLazyRouteImport = createFileRoute('/games/detective')()
const GamesCardLazyRouteImport = createFileRoute('/games/card')()
const Games3dLazyRouteImport = createFileRoute('/games/3d')()
const Games2dLazyRouteImport = createFileRoute('/games/2d')()
const GalleryTabIdLazyRouteImport = createFileRoute('/gallery/$tabId')()
const DemosDemoIdLazyRouteImport = createFileRoute('/demos/$demoId')()
const CalcStokesLazyRouteImport = createFileRoute('/calc/stokes')()
const CalcPoincareLazyRouteImport = createFileRoute('/calc/poincare')()
const CalcMuellerLazyRouteImport = createFileRoute('/calc/mueller')()
const CalcJonesLazyRouteImport = createFileRoute('/calc/jones')()

const LearnLazyRoute = LearnLazyRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/learn.lazy').then((d) => d.Route))
const HardwareLazyRoute = HardwareLazyRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/hardware.lazy').then((d) => d.Route))
const ChroniclesLazyRoute = ChroniclesLazyRouteImport.update({
  id: '/chronicles',
  path: '/chronicles',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/chronicles.lazy').then((d) => d.Route))
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/studio.lazy').then((d) => d.Route))
const MerchandiseRoute = MerchandiseRouteImport.update({
  id: '/merchandise',
  path: '/merchandise',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/merchandise.lazy').then((d) => d.Route))
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/course.lazy').then((d) => d.Route))
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ResearchIndexLazyRoute = ResearchIndexLazyRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/research.index.lazy').then((d) => d.Route),
)
const GamesIndexLazyRoute = GamesIndexLazyRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/games.index.lazy').then((d) => d.Route))
const GalleryIndexLazyRoute = GalleryIndexLazyRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/gallery.index.lazy').then((d) => d.Route))
const CalcIndexLazyRoute = CalcIndexLazyRouteImport.update({
  id: '/calc/',
  path: '/calc/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/calc.index.lazy').then((d) => d.Route))
const DemosIndexRoute = DemosIndexRouteImport.update({
  id: '/demos/',
  path: '/demos/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/demos.index.lazy').then((d) => d.Route))
const ResearchApplicationsLazyRoute =
  ResearchApplicationsLazyRouteImport.update({
    id: '/research/applications',
    path: '/research/applications',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/research.applications.lazy').then((d) => d.Route),
  )
const GamesEscapeLazyRoute = GamesEscapeLazyRouteImport.update({
  id: '/games/escape',
  path: '/games/escape',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/games.escape.lazy').then((d) => d.Route))
const GamesDetectiveLazyRoute = GamesDetectiveLazyRouteImport.update({
  id: '/games/detective',
  path: '/games/detective',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/games.detective.lazy').then((d) => d.Route),
)
const GamesCardLazyRoute = GamesCardLazyRouteImport.update({
  id: '/games/card',
  path: '/games/card',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/games.card.lazy').then((d) => d.Route))
const Games3dLazyRoute = Games3dLazyRouteImport.update({
  id: '/games/3d',
  path: '/games/3d',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/games.3d.lazy').then((d) => d.Route))
const Games2dLazyRoute = Games2dLazyRouteImport.update({
  id: '/games/2d',
  path: '/games/2d',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/games.2d.lazy').then((d) => d.Route))
const GalleryTabIdLazyRoute = GalleryTabIdLazyRouteImport.update({
  id: '/gallery/$tabId',
  path: '/gallery/$tabId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/gallery.$tabId.lazy').then((d) => d.Route),
)
const DemosDemoIdLazyRoute = DemosDemoIdLazyRouteImport.update({
  id: '/demos/$demoId',
  path: '/demos/$demoId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/demos.$demoId.lazy').then((d) => d.Route))
const CalcStokesLazyRoute = CalcStokesLazyRouteImport.update({
  id: '/calc/stokes',
  path: '/calc/stokes',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/calc.stokes.lazy').then((d) => d.Route))
const CalcPoincareLazyRoute = CalcPoincareLazyRouteImport.update({
  id: '/calc/poincare',
  path: '/calc/poincare',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/calc.poincare.lazy').then((d) => d.Route))
const CalcMuellerLazyRoute = CalcMuellerLazyRouteImport.update({
  id: '/calc/mueller',
  path: '/calc/mueller',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/calc.mueller.lazy').then((d) => d.Route))
const CalcJonesLazyRoute = CalcJonesLazyRouteImport.update({
  id: '/calc/jones',
  path: '/calc/jones',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/calc.jones.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$': typeof SplatRoute
  '/course': typeof CourseRoute
  '/merchandise': typeof MerchandiseRoute
  '/studio': typeof StudioRoute
  '/chronicles': typeof ChroniclesLazyRoute
  '/hardware': typeof HardwareLazyRoute
  '/learn': typeof LearnLazyRoute
  '/calc/jones': typeof CalcJonesLazyRoute
  '/calc/mueller': typeof CalcMuellerLazyRoute
  '/calc/poincare': typeof CalcPoincareLazyRoute
  '/calc/stokes': typeof CalcStokesLazyRoute
  '/demos/$demoId': typeof DemosDemoIdLazyRoute
  '/gallery/$tabId': typeof GalleryTabIdLazyRoute
  '/games/2d': typeof Games2dLazyRoute
  '/games/3d': typeof Games3dLazyRoute
  '/games/card': typeof GamesCardLazyRoute
  '/games/detective': typeof GamesDetectiveLazyRoute
  '/games/escape': typeof GamesEscapeLazyRoute
  '/research/applications': typeof ResearchApplicationsLazyRoute
  '/demos/': typeof DemosIndexRoute
  '/calc/': typeof CalcIndexLazyRoute
  '/gallery/': typeof GalleryIndexLazyRoute
  '/games/': typeof GamesIndexLazyRoute
  '/research/': typeof ResearchIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$': typeof SplatRoute
  '/course': typeof CourseRoute
  '/merchandise': typeof MerchandiseRoute
  '/studio': typeof StudioRoute
  '/chronicles': typeof ChroniclesLazyRoute
  '/hardware': typeof HardwareLazyRoute
  '/learn': typeof LearnLazyRoute
  '/calc/jones': typeof CalcJonesLazyRoute
  '/calc/mueller': typeof CalcMuellerLazyRoute
  '/calc/poincare': typeof CalcPoincareLazyRoute
  '/calc/stokes': typeof CalcStokesLazyRoute
  '/demos/$demoId': typeof DemosDemoIdLazyRoute
  '/gallery/$tabId': typeof GalleryTabIdLazyRoute
  '/games/2d': typeof Games2dLazyRoute
  '/games/3d': typeof Games3dLazyRoute
  '/games/card': typeof GamesCardLazyRoute
  '/games/detective': typeof GamesDetectiveLazyRoute
  '/games/escape': typeof GamesEscapeLazyRoute
  '/research/applications': typeof ResearchApplicationsLazyRoute
  '/demos': typeof DemosIndexRoute
  '/calc': typeof CalcIndexLazyRoute
  '/gallery': typeof GalleryIndexLazyRoute
  '/games': typeof GamesIndexLazyRoute
  '/research': typeof ResearchIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/$': typeof SplatRoute
  '/course': typeof CourseRoute
  '/merchandise': typeof MerchandiseRoute
  '/studio': typeof StudioRoute
  '/chronicles': typeof ChroniclesLazyRoute
  '/hardware': typeof HardwareLazyRoute
  '/learn': typeof LearnLazyRoute
  '/calc/jones': typeof CalcJonesLazyRoute
  '/calc/mueller': typeof CalcMuellerLazyRoute
  '/calc/poincare': typeof CalcPoincareLazyRoute
  '/calc/stokes': typeof CalcStokesLazyRoute
  '/demos/$demoId': typeof DemosDemoIdLazyRoute
  '/gallery/$tabId': typeof GalleryTabIdLazyRoute
  '/games/2d': typeof Games2dLazyRoute
  '/games/3d': typeof Games3dLazyRoute
  '/games/card': typeof GamesCardLazyRoute
  '/games/detective': typeof GamesDetectiveLazyRoute
  '/games/escape': typeof GamesEscapeLazyRoute
  '/research/applications': typeof ResearchApplicationsLazyRoute
  '/demos/': typeof DemosIndexRoute
  '/calc/': typeof CalcIndexLazyRoute
  '/gallery/': typeof GalleryIndexLazyRoute
  '/games/': typeof GamesIndexLazyRoute
  '/research/': typeof ResearchIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/course'
    | '/merchandise'
    | '/studio'
    | '/chronicles'
    | '/hardware'
    | '/learn'
    | '/calc/jones'
    | '/calc/mueller'
    | '/calc/poincare'
    | '/calc/stokes'
    | '/demos/$demoId'
    | '/gallery/$tabId'
    | '/games/2d'
    | '/games/3d'
    | '/games/card'
    | '/games/detective'
    | '/games/escape'
    | '/research/applications'
    | '/demos/'
    | '/calc/'
    | '/gallery/'
    | '/games/'
    | '/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/course'
    | '/merchandise'
    | '/studio'
    | '/chronicles'
    | '/hardware'
    | '/learn'
    | '/calc/jones'
    | '/calc/mueller'
    | '/calc/poincare'
    | '/calc/stokes'
    | '/demos/$demoId'
    | '/gallery/$tabId'
    | '/games/2d'
    | '/games/3d'
    | '/games/card'
    | '/games/detective'
    | '/games/escape'
    | '/research/applications'
    | '/demos'
    | '/calc'
    | '/gallery'
    | '/games'
    | '/research'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/course'
    | '/merchandise'
    | '/studio'
    | '/chronicles'
    | '/hardware'
    | '/learn'
    | '/calc/jones'
    | '/calc/mueller'
    | '/calc/poincare'
    | '/calc/stokes'
    | '/demos/$demoId'
    | '/gallery/$tabId'
    | '/games/2d'
    | '/games/3d'
    | '/games/card'
    | '/games/detective'
    | '/games/escape'
    | '/research/applications'
    | '/demos/'
    | '/calc/'
    | '/gallery/'
    | '/games/'
    | '/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  SplatRoute: typeof SplatRoute
  CourseRoute: typeof CourseRoute
  MerchandiseRoute: typeof MerchandiseRoute
  StudioRoute: typeof StudioRoute
  ChroniclesLazyRoute: typeof ChroniclesLazyRoute
  HardwareLazyRoute: typeof HardwareLazyRoute
  LearnLazyRoute: typeof LearnLazyRoute
  CalcJonesLazyRoute: typeof CalcJonesLazyRoute
  CalcMuellerLazyRoute: typeof CalcMuellerLazyRoute
  CalcPoincareLazyRoute: typeof CalcPoincareLazyRoute
  CalcStokesLazyRoute: typeof CalcStokesLazyRoute
  DemosDemoIdLazyRoute: typeof DemosDemoIdLazyRoute
  GalleryTabIdLazyRoute: typeof GalleryTabIdLazyRoute
  Games2dLazyRoute: typeof Games2dLazyRoute
  Games3dLazyRoute: typeof Games3dLazyRoute
  GamesCardLazyRoute: typeof GamesCardLazyRoute
  GamesDetectiveLazyRoute: typeof GamesDetectiveLazyRoute
  GamesEscapeLazyRoute: typeof GamesEscapeLazyRoute
  ResearchApplicationsLazyRoute: typeof ResearchApplicationsLazyRoute
  DemosIndexRoute: typeof DemosIndexRoute
  CalcIndexLazyRoute: typeof CalcIndexLazyRoute
  GalleryIndexLazyRoute: typeof GalleryIndexLazyRoute
  GamesIndexLazyRoute: typeof GamesIndexLazyRoute
  ResearchIndexLazyRoute: typeof ResearchIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicles': {
      id: '/chronicles'
      path: '/chronicles'
      fullPath: '/chronicles'
      preLoaderRoute: typeof ChroniclesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchandise': {
      id: '/merchandise'
      path: '/merchandise'
      fullPath: '/merchandise'
      preLoaderRoute: typeof MerchandiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc/': {
      id: '/calc/'
      path: '/calc'
      fullPath: '/calc/'
      preLoaderRoute: typeof CalcIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/': {
      id: '/demos/'
      path: '/demos'
      fullPath: '/demos/'
      preLoaderRoute: typeof DemosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/applications': {
      id: '/research/applications'
      path: '/research/applications'
      fullPath: '/research/applications'
      preLoaderRoute: typeof ResearchApplicationsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/escape': {
      id: '/games/escape'
      path: '/games/escape'
      fullPath: '/games/escape'
      preLoaderRoute: typeof GamesEscapeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/detective': {
      id: '/games/detective'
      path: '/games/detective'
      fullPath: '/games/detective'
      preLoaderRoute: typeof GamesDetectiveLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/card': {
      id: '/games/card'
      path: '/games/card'
      fullPath: '/games/card'
      preLoaderRoute: typeof GamesCardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/3d': {
      id: '/games/3d'
      path: '/games/3d'
      fullPath: '/games/3d'
      preLoaderRoute: typeof Games3dLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/2d': {
      id: '/games/2d'
      path: '/games/2d'
      fullPath: '/games/2d'
      preLoaderRoute: typeof Games2dLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$tabId': {
      id: '/gallery/$tabId'
      path: '/gallery/$tabId'
      fullPath: '/gallery/$tabId'
      preLoaderRoute: typeof GalleryTabIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/$demoId': {
      id: '/demos/$demoId'
      path: '/demos/$demoId'
      fullPath: '/demos/$demoId'
      preLoaderRoute: typeof DemosDemoIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc/stokes': {
      id: '/calc/stokes'
      path: '/calc/stokes'
      fullPath: '/calc/stokes'
      preLoaderRoute: typeof CalcStokesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc/poincare': {
      id: '/calc/poincare'
      path: '/calc/poincare'
      fullPath: '/calc/poincare'
      preLoaderRoute: typeof CalcPoincareLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc/mueller': {
      id: '/calc/mueller'
      path: '/calc/mueller'
      fullPath: '/calc/mueller'
      preLoaderRoute: typeof CalcMuellerLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc/jones': {
      id: '/calc/jones'
      path: '/calc/jones'
      fullPath: '/calc/jones'
      preLoaderRoute: typeof CalcJonesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  SplatRoute: SplatRoute,
  CourseRoute: CourseRoute,
  MerchandiseRoute: MerchandiseRoute,
  StudioRoute: StudioRoute,
  ChroniclesLazyRoute: ChroniclesLazyRoute,
  HardwareLazyRoute: HardwareLazyRoute,
  LearnLazyRoute: LearnLazyRoute,
  CalcJonesLazyRoute: CalcJonesLazyRoute,
  CalcMuellerLazyRoute: CalcMuellerLazyRoute,
  CalcPoincareLazyRoute: CalcPoincareLazyRoute,
  CalcStokesLazyRoute: CalcStokesLazyRoute,
  DemosDemoIdLazyRoute: DemosDemoIdLazyRoute,
  GalleryTabIdLazyRoute: GalleryTabIdLazyRoute,
  Games2dLazyRoute: Games2dLazyRoute,
  Games3dLazyRoute: Games3dLazyRoute,
  GamesCardLazyRoute: GamesCardLazyRoute,
  GamesDetectiveLazyRoute: GamesDetectiveLazyRoute,
  GamesEscapeLazyRoute: GamesEscapeLazyRoute,
  ResearchApplicationsLazyRoute: ResearchApplicationsLazyRoute,
  DemosIndexRoute: DemosIndexRoute,
  CalcIndexLazyRoute: CalcIndexLazyRoute,
  GalleryIndexLazyRoute: GalleryIndexLazyRoute,
  GamesIndexLazyRoute: GamesIndexLazyRoute,
  ResearchIndexLazyRoute: ResearchIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
